//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_Development_Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application_Development_Project.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Target.
        /// </summary>
        internal static string aboveTargetLabel {
            get {
                return ResourceManager.GetString("aboveTargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string addressLabel {
            get {
                return ResourceManager.GetString("addressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree to Terms of Service.
        /// </summary>
        internal static string agreeCheckBox {
            get {
                return ResourceManager.GetString("agreeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Allowed Number of Attempts:.
        /// </summary>
        internal static string AttemptsLabel {
            get {
                return ResourceManager.GetString("AttemptsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Target.
        /// </summary>
        internal static string belowTargetLabel {
            get {
                return ResourceManager.GetString("belowTargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Birth:.
        /// </summary>
        internal static string BirthLabel {
            get {
                return ResourceManager.GetString("BirthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add as Icon.
        /// </summary>
        internal static string buttonToIcon {
            get {
                return ResourceManager.GetString("buttonToIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Attempts.
        /// </summary>
        internal static string changeAttemptsButton {
            get {
                return ResourceManager.GetString("changeAttemptsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Attempts.
        /// </summary>
        internal static string changeAttemptsButton2 {
            get {
                return ResourceManager.GetString("changeAttemptsButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new icon image for GMMS *must be .ico type image*.
        /// </summary>
        internal static string changeIconImageLabel {
            get {
                return ResourceManager.GetString("changeIconImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string changePasswordButton {
            get {
                return ResourceManager.GetString("changePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Gym Member.
        /// </summary>
        internal static string createGymMemberButton {
            get {
                return ResourceManager.GetString("createGymMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number:.
        /// </summary>
        internal static string creditCardNumber {
            get {
                return ResourceManager.GetString("creditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        internal static string customizeLogoApp {
            get {
                return ResourceManager.GetString("customizeLogoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Membership.
        /// </summary>
        internal static string deactivateMemberButton {
            get {
                return ResourceManager.GetString("deactivateMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Deactivation Reasons.
        /// </summary>
        internal static string deactivationReasonLabel {
            get {
                return ResourceManager.GetString("deactivationReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reasons.
        /// </summary>
        internal static string deactivationReasonTabPage {
            get {
                return ResourceManager.GetString("deactivationReasonTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address:.
        /// </summary>
        internal static string emailAddressLabel {
            get {
                return ResourceManager.GetString("emailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring Soon.
        /// </summary>
        internal static string expirationTabPage {
            get {
                return ResourceManager.GetString("expirationTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New system password will  be applied on next login.
        /// </summary>
        internal static string instructionLabel {
            get {
                return ResourceManager.GetString("instructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this link.
        /// </summary>
        internal static string linkLabelTutorial {
            get {
                return ResourceManager.GetString("linkLabelTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Picture.
        /// </summary>
        internal static string loadPicture {
            get {
                return ResourceManager.GetString("loadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginPageTab {
            get {
                return ResourceManager.GetString("loginPageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Member.
        /// </summary>
        internal static string mainFormTabPage {
            get {
                return ResourceManager.GetString("mainFormTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        internal static string newPassLabel {
            get {
                return ResourceManager.GetString("newPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If successful, application will restart.
        /// </summary>
        internal static string newPassNotifLabel {
            get {
                return ResourceManager.GetString("newPassNotifLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password:.
        /// </summary>
        internal static string oldPassLabel {
            get {
                return ResourceManager.GetString("oldPassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Target.
        /// </summary>
        internal static string onTargetLabel {
            get {
                return ResourceManager.GetString("onTargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string phoneNumberLabel {
            get {
                return ResourceManager.GetString("phoneNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string phoneNumberLabel2 {
            get {
                return ResourceManager.GetString("phoneNumberLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please watch the following tutorial to familiarize yourself with the application.
        /// </summary>
        internal static string pleaseWatchLabel {
            get {
                return ResourceManager.GetString("pleaseWatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivate Membership.
        /// </summary>
        internal static string reactivateMemberButton {
            get {
                return ResourceManager.GetString("reactivateMemberButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string removeScreenButton {
            get {
                return ResourceManager.GetString("removeScreenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Membership.
        /// </summary>
        internal static string renewButton {
            get {
                return ResourceManager.GetString("renewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Membership.
        /// </summary>
        internal static string renewButton2 {
            get {
                return ResourceManager.GetString("renewButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetPageTab {
            get {
                return ResourceManager.GetString("resetPageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetPasswordlabel {
            get {
                return ResourceManager.GetString("resetPasswordlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string revenueTabPage {
            get {
                return ResourceManager.GetString("revenueTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string searchButton {
            get {
                return ResourceManager.GetString("searchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up.
        /// </summary>
        internal static string searchMemberTabPage {
            get {
                return ResourceManager.GetString("searchMemberTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Security.
        /// </summary>
        internal static string SecurityTabPage {
            get {
                return ResourceManager.GetString("SecurityTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to GMMS.
        /// </summary>
        internal static string titleLabel {
            get {
                return ResourceManager.GetString("titleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Service:
        ///
        ///• Member Ships have to be paid on a yearly basis 
        ///
        ///• Yearly Membership cost is 120$
        ///
        ///• Credit Card Only
        ///
        ///• Members Must be Respectful At All Times
        ///
        ///• No Refunds 
        /// 
        ///• When Membership Expires, Members Must Pay $120 To Get Access To The Gym Again.
        /// </summary>
        internal static string tosLabel {
            get {
                return ResourceManager.GetString("tosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Revenue.
        /// </summary>
        internal static string totalRevenueLabel {
            get {
                return ResourceManager.GetString("totalRevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string tutorialTabPage {
            get {
                return ResourceManager.GetString("tutorialTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string viewAllGymMemberTab {
            get {
                return ResourceManager.GetString("viewAllGymMemberTab", resourceCulture);
            }
        }
    }
}
